# Generated by Django 4.2.1 on 2023-05-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fining', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={},
        ),
    ]
