# Generated by Django 4.2.1 on 2023-05-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='regLocation',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='registered_lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='registered_long',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='location_lat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='location_long',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
