# Generated by Django 4.2.1 on 2023-05-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_remove_motorcycle_reglocation_remove_report_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='registered_lat',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='registered_long',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
